# Generated by Django 4.0.5 on 2022-06-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
