# Generated by Django 4.0.4 on 2022-05-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to='menu_imgs/')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
