"""Generated by Django 4.1.3 on 2022-06-15 11:16"""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """migration file for menu app"""

    dependencies = [
        ('menu', '0003_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                primary_key=True, serialize=False, verbose_name='ID')),
                ('dishName', models.CharField(max_length=20)),
                ('dishDesc', models.TextField()),
                ('dishPrice', models.IntegerField()),
                ('dishPrepTime', models.IntegerField()),
                ('dishImage', models.ImageField(upload_to='menu_imgs/')),
                ('category', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='menu.category')),
            ],
        ),
    ]
